# Generated by Django 5.0.7 on 2024-08-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='destination_images/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('continent', models.CharField(choices=[('AF', 'África'), ('AS', 'Ásia'), ('EU', 'Europa'), ('NA', 'América do Norte'), ('SA', 'América do Sul'), ('OC', 'Oceania'), ('AN', 'Antártica')], max_length=2)),
            ],
        ),
    ]
