# Generated by Django 5.0.7 on 2024-08-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('description', models.TextField()),
                ('continent', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='destinations',
            field=models.ManyToManyField(to='wishlist.destination'),
        ),
    ]
