# Generated by Django 5.1 on 2024-08-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('wishlist', '0002_destination_alter_wishlist_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='destinations',
            field=models.ManyToManyField(to='destinations.destination'),
        ),
    ]
